version: '2'
services:
  #
  # [ server stack ]
  #
  # - postgres + pg_adm
  #

  db:
    restart: always
    # comment on build if want to use the dockerhub build
    build:
      context: .
      dockerfile: Dockerfile
    image: benizar/pg_adm
    container_name: pg_adm
    # redirect to 5433 in case you already have postgres installed
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
